import os
import re
from datetime import datetime

LOG_FILE_PATH = "netpulse_security_incidents.log"
REPORT_FILE_PATH = "netpulse_executive_summary.md"

def parse_logs_and_generate_report():
    print("--- Reading Security Incident Logs ---")
    
    if not os.path.exists(LOG_FILE_PATH):
        print(f"[ERROR] Log file '{LOG_FILE_PATH}' not found. Please run the dashboard tools first to generate logs!")
        return

    # Counter metrics
    total_entries = 0
    info_count = 0
    warning_count = 0
    critical_count = 0
    
    incident_timeline = []
    warnings_list = []

    # Regular expression to parse our custom log format: Timestamp | [LEVEL] | Message
    log_pattern = re.compile(r"^([\d\-\s:]+) \|\s+\[([A-Z]+)\]\s+\|\s+(.*)$")

    with open(LOG_FILE_PATH, "r") as f:
        for line in f:
            match = log_pattern.match(line.strip())
            if match:
                total_entries += 1
                timestamp, level, message = match.groups()
                
                if level == "INFO":
                    info_count += 1
                    # Track major baseline/retraining successes in timeline
                    if "Recall" in message or "complete" in message:
                        incident_timeline.append((timestamp, "System Optimization", message))
                elif level == "WARNING":
                    warning_count += 1
                    warnings_list.append((timestamp, message))
                elif level == "CRITICAL":
                    critical_count += 1
                    incident_timeline.append((timestamp, "THREAT ALERT", message))

    print("--- Compiling Executive Security Markdown Report ---")
    
    # Generate a clean Markdown report
    with open(REPORT_FILE_PATH, "w") as r:
        r.write("# NetPulse IDS - Executive Security Audit Report 🛡️\n\n")
        r.write(f"**Report Generated On:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        r.write(f"**Source Audit Log:** `{LOG_FILE_PATH}`\n\n")
        r.write("---\n\n")
        
        r.write("## 📊 Executive Metric Summary\n")
        r.write("Below is the operational health metric breakdown extracted from live pipeline execution histories:\n\n")
        r.write("| Metric Severity Level | Total Logged Events | Operational Significance |\n")
        r.write("| :--- | :---: | :--- |\n")
        r.write(f"| 🟢 **INFO** | {info_count} | Standard pipeline starts, data loads, and safe updates |\n")
        r.write(f"| 🟡 **WARNING** | {warning_count} | Threshold drops, drift detections, and performance decays |\n")
        r.write(f"| 🔴 **CRITICAL** | {critical_count} | Active malicious threat signatures and severe anomalies |\n")
        r.write(f"| 🔢 **TOTAL AUDITS** | {total_entries} | Aggregated forensic ledger entries |\n\n")
        
        r.write("---\n\n")
        
        r.write("## ⚠️ Detected System Vulnerabilities & Performance Drops\n")
        if warnings_list:
            r.write("The system flagged the following operational exceptions where model metrics dropped below guardrail conditions:\n\n")
            for ts, msg in warnings_list:
                r.write(f"* **[{ts}]** {msg}\n")
        else:
            r.write("✅ No critical security parameter drops or model performance degradation events detected.\n")
            
        r.write("\n---\n\n")
        
        r.write("## ⏳ Security Incident & Adaptation Timeline\n")
        r.write("Chronological ledger of active attack interceptions and automated system recoveries:\n\n")
        if incident_timeline:
            for ts, event_type, msg in incident_timeline:
                icon = "🚨" if event_type == "THREAT ALERT" else "⚙️"
                r.write(f"### {icon} {event_type} - {ts}\n")
                r.write(f"> {msg}\n\n")
        else:
            r.write("*No notable security incidents or adaptation events recorded in this tracking cycle.*\n")
            
        r.write("\n\n**Confidentiality Notice:** *This report is automatically generated by the NetPulse IDS telemetry subsystem. Unauthorized distribution is prohibited.*")

    print(f"Success! Executive report compiled cleanly as '{REPORT_FILE_PATH}'")

if __name__ == "__main__":
    parse_logs_and_generate_report()